Feature/movies list
winmord/MtsTetaHomework pull request #3
Opened 2021-07-17 18:51 UTC by winmord

ДЗ 4: Lists

2021-07-20 21:44 UTC, maxlord requested changes

2021-07-20 21:44 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/presentation/recyclerviews/adapters/CategoriesRecyclerAdapter.kt
> +        holder.itemView.setOnClickListener { callbackFunction(categories[position].name) }
Листенер можно создавать в конструкторе, а чтобы понять какой объект кликнут, можно хранить его в теге вьюшки, или создавать локальное поле и сетить его в методе bind().

2021-07-20 21:44 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/presentation/recyclerviews/adapters/MoviesRecyclerAdapter.kt
> +const val TYPE_EMPTY = 0
лучше добавить private

2021-07-20 21:44 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/presentation/recyclerviews/diffutils/callbacks/CategoriesCallback.kt
> +) :
Форматирование

2021-07-20 21:44 UTC, maxlord commented on app/src/main/res/layout-land/fragment_movie_details.xml
> +        android:id="@+id/movieCoverImageView"
Префиксы к вьюшкам: ivMovieCover, textTitle, и т.д.

2021-07-20 21:44 UTC, maxlord commented on app/src/main/res/values/styles.xml
> +    <style name="RoundedImageView.Corner10">
Лучше не использовать размер в имени, позже ты поменяешь димен, а тут останется.
Сразу надо называть более осмысленно, типа small, normal, large и т.д.

2021-07-21 18:47 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/presentation/recyclerviews/adapters/MoviesRecyclerAdapter.kt
> +const val TYPE_EMPTY = 0
Добавил.

2021-07-21 18:49 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/presentation/recyclerviews/diffutils/callbacks/CategoriesCallback.kt
> +) :
Поправил.

2021-07-21 19:27 UTC, winmord commented on app/src/main/res/values/styles.xml
> +    <style name="RoundedImageView.Corner10">
Переименовал в SmallCorner и NormalCorner

2021-07-21 19:38 UTC, winmord commented on app/src/main/res/layout-land/fragment_movie_details.xml
> +        android:id="@+id/movieCoverImageView"
Исправил id вьюшек.

2021-07-21 21:45 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/presentation/recyclerviews/adapters/CategoriesRecyclerAdapter.kt
> +        holder.itemView.setOnClickListener { callbackFunction(categories[position].name) }
Исправил.

2021-07-23 14:49 UTC, maxlord requested changes

2021-07-23 14:49 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/presentation/recyclerviews/viewholders/MoviesViewHolder.kt
> +    private lateinit var item: String
Идея была же в том, что весь item хранить, и передавать его.

2021-07-23 14:54 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/presentation/recyclerviews/viewholders/MoviesViewHolder.kt
> +    private lateinit var item: String
Исправил.

2021-07-24 10:16 UTC, merged