Feature/menu
winmord/MtsTetaHomework pull request #4
Opened 2021-07-24 15:45 UTC by winmord

ДЗ 5

2021-07-26 09:43 UTC, maxlord requested changes

2021-07-26 09:43 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/presentation/MainActivity.kt
> +        supportActionBar?.hide()
А ты разве не юзаешь тему .NoActionBar?

2021-07-26 09:43 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/HomeFragment.kt
> +        initDataSource()
1. Лучше это все вынести в отдельный метод loadData()
2. И любую загрузку делать в колбеке onViewCreated()

2021-07-26 09:43 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/HomeFragment.kt
> +            val bundle = bundleOf("movieDto" to it)
название ключей бандла надо выносить в константы, и называются они обычно в lowercase_underscore-стиле

2021-07-26 09:43 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/MovieDetailsFragment.kt
> +        view.findViewById<TextView>(R.id.textMovieTitle).text = movieDto?.title
Лучше будет, если ты вынесешь вьюшки в переменные класса, сделаешь метод initViews(), где ты все их найдешь
textMoviewTitle = view.findViewById<TextView>(R.id.textMovieTitle)
а уже в методе loadData() загрузишь в них данные. 

Так будет читаемее, а то сейчас все сливается в одну кучу.

2021-07-26 09:43 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/ProfileFragment.kt
> +    override fun onCreateView(
В этом методе должна только вьюшка создаваться.
Не перегружай его другой логикой.
Загрузку данных производи в методе onViewCreated()

2021-07-26 09:43 UTC, maxlord commented on app/src/main/res/drawable/selector.xml
> +<selector xmlns:android="http://schemas.android.com/apk/res/android">
А если еще один селектор появится, как назовешь?
Старайся сразу давайть осмысленные имена ресурсами, переменным и т.д.

2021-07-26 17:27 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/presentation/MainActivity.kt
> +        supportActionBar?.hide()
Юзал, но неправильно начал устанавливать navController. Разобрался в чём ошибка и вернул тему .NoActionBar.

2021-07-26 17:31 UTC, winmord commented on app/src/main/res/drawable/selector.xml
> +<selector xmlns:android="http://schemas.android.com/apk/res/android">
Выбрал осмысленное имя.

2021-07-26 17:44 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/HomeFragment.kt
> +            val bundle = bundleOf("movieDto" to it)
Вынес в константу с осмысленным именем.

2021-07-26 18:26 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/HomeFragment.kt
> +        initDataSource()
Сделал для все фрагментов.

2021-07-26 18:26 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/MovieDetailsFragment.kt
> +        view.findViewById<TextView>(R.id.textMovieTitle).text = movieDto?.title
Вьюшки в переменные вынес, метод loadData реализовал.

2021-07-26 18:27 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/ProfileFragment.kt
> +    override fun onCreateView(
Создал метод loadData и всё вынес в него. Вызываю в onViewCreated().

2021-07-27 15:01 UTC, maxlord requested changes

2021-07-27 15:01 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/HomeFragment.kt
> +            val bundle = bundleOf(movie_dto_bundle_key to it)
Константы капсом нужно называть

2021-07-27 15:32 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/HomeFragment.kt
> +            val bundle = bundleOf(movie_dto_bundle_key to it)
Переименовал

2021-07-27 15:49 UTC, maxlord approved these changes

2021-07-28 09:51 UTC, merged