Feature/multithreading
winmord/MtsTetaHomework pull request #5
Opened 2021-07-29 23:15 UTC by winmord

ДЗ 6

2021-07-30 17:05 UTC, maxlord requested changes

2021-07-30 17:05 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/data/features/movies/MoviesDataSourceImpl.kt
> +        Thread.sleep(2000)
Тут лучше не слипить, слипить нужно в месте вызова, например в активити/фрагменте.
Метод должен отвечать своим требованиям. В данном случае - он должен вернуть список фильмов.
Ничего дополнительно он делать не должен. 
SRP - Single Responsibility Principle.

2021-07-30 17:05 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/HomeFragment.kt
> +        categoriesAdapter.categories = categories
Это лучше делать в отдельном методе или после инициализации.
по сути метод `setupAdapters()` должен отвечать только за инициализацию адаптеров.

2021-07-30 17:05 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/HomeFragment.kt
> +                movies = moviesModel.getMovies()
Вот тут ты можешь заслипить, причем 1 раз, а не в каждом методе к примеру.

2021-07-30 17:05 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/HomeFragment.kt
> +            withContext(Dispatchers.Main) {
Полагаю, это лишнее, ты итак находишься в Main-контексте.
В корутинах код последовательный.
Смотри:
Ты находишь в Main-диспетчере, из него уходишь на IO, после получения данных ты возвращаешься в Main.
Я думаю второй вызов Main-дистпетчера лишний.

2021-07-30 17:05 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/HomeFragment.kt
> +            withContext(Dispatchers.Main) {
Проверь на всякий случай.

2021-07-30 18:34 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/data/features/movies/MoviesDataSourceImpl.kt
> +        Thread.sleep(2000)
Перенёс в updateData().

2021-07-30 18:35 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/HomeFragment.kt
> +                movies = moviesModel.getMovies()
Перенёс.

2021-07-30 18:37 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/HomeFragment.kt
> +            withContext(Dispatchers.Main) {
Да, вызов действительно лишний - всё хорошо и без него. Убрал.

2021-07-30 18:41 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/HomeFragment.kt
> +        categoriesAdapter.categories = categories
Перенёс в отдельный метод setupInitAdaptersData().

2021-08-03 10:47 UTC, maxlord requested changes

2021-08-03 10:47 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/HomeFragment.kt
> +    private fun setupInitAdaptersData() {
setup, init глаголы, имеющие примерно одинаковое значение 
setAdapterData или setupAdapterData

2021-08-03 10:47 UTC, maxlord commented on app/src/main/res/layout/fragment_home.xml
> +            android:id="@+id/buttonSearch"
btSearch

2021-08-03 10:53 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/presentation/fragments/HomeFragment.kt
> +    private fun setupInitAdaptersData() {
Переименовал в setupAdapterData.

2021-08-03 10:53 UTC, winmord commented on app/src/main/res/layout/fragment_home.xml
> +            android:id="@+id/buttonSearch"
Переименовал.

2021-08-03 13:24 UTC, maxlord approved these changes

2021-08-05 18:36 UTC, maxlord approved these changes

2021-08-10 10:27 UTC, maxlord approved these changes

2021-08-10 12:16 UTC, merged