Feature/mvvm
winmord/MtsTetaHomework pull request #6
Opened 2021-08-16 22:01 UTC by winmord

ДЗ 7

2021-08-19 10:20 UTC, maxlord requested changes

2021-08-19 10:20 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/model/features/preferences/PreferencesDataSource.kt
> +    fun getPreferences(): List<CategoryDto>
getCategories()

2021-08-19 10:20 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/viewmodel/HomeViewModel.kt
> +            withContext(Dispatchers.IO) {
тут лучше запустить скоуп на IO, там выполнить getCategories() и уже на Main отправить данные в лайв-дату.

2021-08-19 10:20 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/viewmodel/HomeViewModel.kt
> +            withContext(Dispatchers.IO) {
Судя по твоему коду ты Main вообще никак не задействуешь.

2021-08-19 10:20 UTC, maxlord commented on app/src/main/java/com/mtsteta/homework/viewmodel/ProfileViewModel.kt
> +                _preferencesDataList.postValue(preferencesModel.getPreferences())
Та же проблема, нужно разделить Main и IO и операции в них.

2021-08-19 16:03 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/model/features/preferences/PreferencesDataSource.kt
> +    fun getPreferences(): List<CategoryDto>
Переименовал.

2021-08-19 16:08 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/viewmodel/HomeViewModel.kt
> +            withContext(Dispatchers.IO) {
Исправил.

2021-08-19 16:08 UTC, winmord commented on app/src/main/java/com/mtsteta/homework/viewmodel/ProfileViewModel.kt
> +                _preferencesDataList.postValue(preferencesModel.getPreferences())
Исправил.

2021-08-20 10:45 UTC, maxlord approved these changes

2021-08-23 20:08 UTC, merged